const Routes = {
  IntroSlider: "IntroSliderPage",
  SigninPage: "SigninPage",
  SignUpPage: "SignUpPage",
  PDetialsForm: "PersonInfoPage",
  PersonalDetails: "PersonalDetailsPage",
  HomePage: "HomePage",
  ProductsPage: "ProductsPage",
  WalletPage: "WalletPage",
  MyProfilePage: "MyProfilePage",
  MyDetailsPage: "MyDetailsPage",
  NotificationsPage: "NotificationsPage",
  ShopItemPage: "ShopItemPage",
  CartItemPage: "CartItemPage",
  PaymentDetailsPage: "PaymentDetailsPage",
  BottomNavigationTab: "BottomNavigationTab",
  Auth: "Auth",
  BottomNavBar: "BottomNavBar",
  ShopItems: "ShopItems",
  Profile: "Profile",
  Main: "Main",
  Wallet: "Wallet",
};
export default Routes;
